# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UAhW2JQM8AgRe8fB0CJbpN_CKFQhKT-j
"""

pip install opencv-python==4.9.0.80 face_recognition==1.3.0 mediapipe==0.10.14 deepface==0.0.93 mtcnn==0.1.1 numpy==1.26.4 Pillow==10.3.0 scikit-image==0.22.0 imagehash==4.3.1

!ffmpeg -err_detect ignore_err -i /content/video_sample_1.mov -c copy -map 0 fixed_video.mp4

"""To convert a video file to MP4 format using FFmpeg, you can use the following command structure. This command will re-encode the video using the `libx264` codec, which is widely supported, and set a Constant Rate Factor (CRF) of 23 for a good balance of quality and file size. Adjust the CRF value (e.g., 18 for higher quality, 28 for smaller size) as needed."""

!ffmpeg -i my_raw_footage.avi -c:v libx264 -crf 23 -pix_fmt yuv420p my_converted_video.mp4

print("Conversion command executed. Check your files for 'my_converted_video.mp4'.")

import cv2
import numpy as np
import imagehash
from PIL import Image
import json
import subprocess
import os
import time
import base64

# --- Configuration & Thresholds ---
INPUT_VIDEO = "/content/video_sample_1.mov"
OUTPUT_VIDEO = "compressed_output.mp4"
REPORT_HTML = "compression_report.html"
JSON_OUTPUT = "segments_kept.json"

PHASH_SIMILARITY_THRESHOLD = 3  # 64 bits total. Diff <= 3 implies > ~95% similarity
OPTICAL_FLOW_THRESHOLD = 0.05
CONTEXT_INTERVAL_SEC = 3
TARGET_FPS = 12
ANALYSIS_RESOLUTION = (320, 240) # Drastically speeds up Haar and Optical flow

def main():
    print(f"[*] Starting Smart Video Compression on {INPUT_VIDEO}...")
    start_time = time.time()

    # 1. Initialize Video Capture
    if not os.path.exists(INPUT_VIDEO):
        raise FileNotFoundError(f"Input video file not found at: {INPUT_VIDEO}")

    cap = cv2.VideoCapture(INPUT_VIDEO)
    if not cap.isOpened():
        # This means the file exists but OpenCV cannot open it.
        # This could be due to a corrupted file, unsupported codec,
        # or missing backend libraries (e.g., ffmpeg integration issues).
        raise IOError(f"OpenCV cannot open the video file: {INPUT_VIDEO}. "
                      f"The file exists but might be corrupted or use an unsupported codec. "
                      f"Please ensure it's a valid video file and try converting it to a common format like .mp4 if issues persist.")

    original_fps = cap.get(cv2.CAP_PROP_FPS)
    if original_fps == 0: original_fps = 30.0

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    context_interval_frames = int(original_fps * CONTEXT_INTERVAL_SEC)

    # Load Haar Cascade
    cascade_path = cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
    face_cascade = cv2.CascadeClassifier(cascade_path)

    # 2. Setup FFmpeg subprocess pipe for Step 5
    ffmpeg_cmd = [
        'ffmpeg', '-y',
        '-f', 'rawvideo',
        '-vcodec', 'rawvideo',
        '-s', f'{width}x{height}',
        '-pix_fmt', 'bgr24',
        '-r', str(TARGET_FPS),
        '-i', '-',
        '-c:v', 'libx264',
        '-preset', 'ultrafast', # Max encoding speed to hit < 10s benchmark
        '-crf', '28',
        '-pix_fmt', 'yuv420p',
        OUTPUT_VIDEO
    ]

    try:
        ffmpeg_process = subprocess.Popen(ffmpeg_cmd, stdin=subprocess.PIPE, stderr=subprocess.DEVNULL)
    except FileNotFoundError:
        raise SystemError("ffmpeg is not installed or not in PATH. Please install ffmpeg.")

    # State variables
    last_kept_hash = None
    prev_gray_small = None
    last_kept_idx = -context_interval_frames # Force frame 0 to be kept as context

    kept_indices = []
    storyboard_base64 = []

    print("[*] Processing frames...")

    frame_idx = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Fast path downscaling for algorithm steps
        small_frame = cv2.resize(frame, ANALYSIS_RESOLUTION)
        gray_small = cv2.cvtColor(small_frame, cv2.COLOR_BGR2GRAY)

        keep_frame = False
        reason = ""

        # Step 4: Context Frame Check
        if (frame_idx - last_kept_idx) >= context_interval_frames:
            keep_frame = True
            reason = "Context"

        if not keep_frame:
            # Step 1: pHash Check
            current_hash = imagehash.phash(Image.fromarray(gray_small))

            # If we don't drop from pHash, we might still drop from Optical Flow
            drop_from_phash = False
            if last_kept_hash is not None:
                hash_diff = current_hash - last_kept_hash
                if hash_diff <= PHASH_SIMILARITY_THRESHOLD:
                    drop_from_phash = True

            if drop_from_phash:
                # If similar, we skip further heavy checks unless we want Haar to override.
                # Assuming static scenes don't spawn faces without changing pHash.
                keep_frame = False
            else:
                # Step 3: Haar Face Check (Overrides motion drops)
                faces = face_cascade.detectMultiScale(gray_small, 1.1, 3)
                if len(faces) > 0:
                    keep_frame = True
                    reason = "Face Detected"
                else:
                    # Step 2: Optical Flow Check
                    if prev_gray_small is not None:
                        flow = cv2.calcOpticalFlowFarneback(
                            prev_gray_small, gray_small, None,
                            0.5, 3, 15, 3, 5, 1.2, 0
                        )
                        mag, _ = cv2.cartToPolar(flow[..., 0], flow[..., 1])
                        motion_score = np.mean(mag)

                        if motion_score >= OPTICAL_FLOW_THRESHOLD:
                            keep_frame = True
                            reason = "Motion Detected"

        # Action Phase
        if keep_frame:
            # Write full resolution frame to ffmpeg pipe
            ffmpeg_process.stdin.write(frame.tobytes())

            kept_indices.append({
                "frame_index": frame_idx,
                "timestamp_sec": round(frame_idx / original_fps, 3),
                "reason": reason
            })

            last_kept_idx = frame_idx
            last_kept_hash = imagehash.phash(Image.fromarray(gray_small))

            # Save occasional frames for the HTML storyboard (max 6 images)
            if len(storyboard_base64) < 6 and len(kept_indices) % max(1, (context_interval_frames//2)) == 0:
                _, buffer = cv2.imencode('.jpg', small_frame)
                b64_str = base64.b64encode(buffer).decode('utf-8')
                storyboard_base64.append(b64_str)

        prev_gray_small = gray_small
        frame_idx += 1

    # Cleanup
    cap.release()
    ffmpeg_process.stdin.close()
    ffmpeg_process.wait()

    end_time = time.time()
    processing_time = round(end_time - start_time, 2)

    # Calculate metrics
    original_size_mb = os.path.getsize(INPUT_VIDEO) / (1024 * 1024) if os.path.exists(INPUT_VIDEO) else 0
    compressed_size_mb = os.path.getsize(OUTPUT_VIDEO) / (1024 * 1024)
    reduction_pct = ((original_size_mb - compressed_size_mb) / original_size_mb) * 100 if original_size_mb > 0 else 0

    # 3. Generate JSON Deliverable
    json_payload = {
        "metadata": {
            "file": INPUT_VIDEO,
            "total_raw_frames": total_frames,
            "kept_frames_count": len(kept_indices),
            "compression_ratio_pct": round(reduction_pct, 2)
        },
        "kept_frames": kept_indices
    }

    with open(JSON_OUTPUT, 'w') as f:
        json.dump(json_payload, f, indent=4)

    # 4. Generate HTML Report (Offline, No CDNs)
    storyboard_html = "".join([f"<img src='data:image/jpeg;base64,{img}' alt='Storyboard Frame'>" for img in storyboard_base64])

    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Compression Report - Sentio</title>
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: #f4f4f9; color: #333; margin: 0; padding: 40px; }}
            .container {{ max-width: 900px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
            .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 30px 0; }}
            .stat-box {{ background: #ecf0f1; padding: 20px; border-radius: 8px; text-align: center; border-top: 4px solid #3498db; }}
            .stat-box h3 {{ margin: 0 0 10px 0; font-size: 14px; color: #7f8c8d; text-transform: uppercase; }}
            .stat-box .value {{ font-size: 28px; font-weight: bold; color: #2c3e50; }}
            .success {{ color: #27ae60; }}
            .storyboard {{ display: flex; gap: 10px; flex-wrap: wrap; margin-top: 20px; justify-content: center; }}
            .storyboard img {{ border-radius: 6px; box-shadow: 0 2px 4px rgba(0,0,0,0.2); width: 250px; height: auto; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Smart Video Compression Report</h1>
            <p>Execution completed successfully. Below are the performance metrics and storyboard extracts.</p>

            <div class="stats-grid">
                <div class="stat-box">
                    <h3>Processing Time</h3>
                    <div class="value">{processing_time}s</div>
                </div>
                <div class="stat-box">
                    <h3>Original Size</h3>
                    <div class="value">{original_size_mb:.2f} MB</div>
                </div>
                <div class="stat-box">
                    <h3>Compressed Size</h3>
                    <div class="value success">{compressed_size_mb:.2f} MB</div>
                </div>
                <div class="stat-box">
                    <h3>Size Reduction</h3>
                    <div class="value success">{reduction_pct:.1f}%</div>
                </div>
                <div class="stat-box">
                    <h3>Frames Kept</h3>
                    <div class="value">{len(kept_indices)} / {total_frames}</div>
                </div>
            </div>

            <h2>Storyboard (Sample Retained Frames)</h2>
            <div class="storyboard">
                {storyboard_html}
            </div>
        </div>
    </body>
    </html>
    """

    with open(REPORT_HTML, 'w') as f:
        f.write(html_content)

    print(f"\n[+] Success! Processing completed in {processing_time} seconds.")
    print(f"[+] Output Video: {OUTPUT_VIDEO} ({compressed_size_mb:.2f} MB)")
    print(f"[+] Report generated: {REPORT_HTML}")
    print(f"[+] JSON Mapping generated: {JSON_OUTPUT}")

if __name__ == "__main__":
    main()

